---
title: "Data Cleaning (screening event)"
author: "Zhiyu Wei"
date: 2025-2-3
output: github_document
---

#### Setup

```{r setup, include = FALSE, warning = FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(patchwork)
library(knitr)
library(sf)
library(lubridate)
library(stringr)
library(leaflet)
library(shiny)
library(leaflet.extras)
library(htmlwidgets)
library(rgeoda)
library(RColorBrewer)
library(classInt)
library(readxl)
event <- read_excel("./dataset/Lumex product screening data_final for capstone.xlsx", sheet=1)
raw <- read_excel("./dataset/Lumex product screening data_final for capstone.xlsx", sheet=2)

```

# Data cleaning
```{r column names and row number}
colnames(raw)[4:6] <- raw[1, 4:6]

colnames(raw)[8:12] <- raw[1, 8:12]

colnames(raw)[16:26] <- raw[1, 16:26]

colnames(raw)[31] <- raw[1, 31]

colnames(raw)[33:36] = raw[1, 33:36]

colnames(raw)[38:43] = raw[1, 38:43]

colnames(raw)[45:46] = raw [1, 45:46]

colnames(raw)[48:50] = raw[1, 48:50]

colnames(raw)[51:53] = raw[1, 51:53]

# remove first row becasue of redundancy
raw <- raw[-1, ]

```


# EDA: Countires, Hg concentration based on Product type (soap/cream)
# Question: should we deduct the fume hood background for the lab result?

# code book: OBR = Office background reading (ng/m3)
# SRB = Storage Room Background (ng/m3)
# FHB = Fume Hood Background (ng/m3)

